#####################################################
# Makefile for the fonts directory of Grace         #
#####################################################
# You should not change anything here.              #
#####################################################

TOP=..

include $(TOP)/Make.conf

all : dummy

tests : dummy

clean : dummy

distclean : dummy

devclean : dummy

install : dummy

links : dummy

dummy :
